[dependencies.icentral-3p]
path = "../icentral-3p"
version = "0.1.0"
[package]
edition = "2021"
name = "icentral-operation"
version = "0.1.0"
description = "A Rust crate that defines an enum for basic operations including insertion and deletion, with essential utilities for operation management."
keywords = ["operation", "insertion", "deletion", "enum", "utilities"]
categories = ["algorithms", "data-structures", "text-processing", "filesystem", "command-line-utilities"]
