[dependencies.icentral-3p]
path = "../icentral-3p"
version = "0.1.0"
[dependencies.icentral-graph-interface]
path = "../icentral-graph-interface"
version = "0.1.0"
[dependencies.icentral-mindexed-map]
path = "../icentral-mindexed-map"
version = "0.1.0"
[dependencies.icentral-nodeid]
path = "../icentral-nodeid"
version = "0.1.0"
[dependencies]
renew-traits = "0.1.0"
[package]
edition = "2021"
name = "icentral-parents-map"
version = "0.1.0"
description = "A Rust crate to manage parent-node relationships with features to add, set, and query parents, suitable for graph-based frameworks."
keywords = ["parents", "nodes", "graph", "relationships", "datastructure"]
categories = ["algorithms", "data-structures", "mathematics", "development-tools"]
license     = "MIT OR Apache-2.0"
