[dependencies.icentral-deps]
path = "../icentral-deps"
version = "0.1.0"
[dependencies.icentral-mindexed-map]
path = "../icentral-mindexed-map"
version = "0.1.0"
[dependencies.icentral-nodeid]
path = "../icentral-nodeid"
version = "0.1.0"
[package]
edition = "2021"
name = "icentral-pair-dependencies"
version = "0.1.0"
description = "icentral-pair-dependencies efficiently manages pair dependencies between nodes using a structured data model supporting fast access and updates."
keywords = ["dependencies", "nodes", "algorithms", "pairing", "simulation"]
categories = ["algorithms", "mathematics", "simulation", "science", "data-structures"]
