[dependencies.icentral-deps]
path = "../icentral-deps"
version = "0.1.0"
[dependencies.icentral-mindexed-map]
path = "../icentral-mindexed-map"
version = "0.1.0"
[dependencies.icentral-nodeid]
path = "../icentral-nodeid"
version = "0.1.0"
[package]
edition = "2021"
name = "icentral-sigmas"
version = "0.1.0"
description = "A Rust library providing efficient management of sigma values for nodes in graph-based data structures. Includes traits for accessing and modifying sigma values, with a focus on performance and precision."
keywords = ["sigma", "node", "graph", "rust", "efficiency"]
categories = ["algorithms", "data-structures", "science", "simulation", "rust-patterns"]
