[dependencies.icentral-3p]
path = "../icentral-3p"
version = "0.1.0"
[dependencies.icentral-nodeid]
path = "../icentral-nodeid"
version = "0.1.0"
[package]
edition = "2021"
name = "icentral-mindexed-map"
version = "0.1.0"
description = "A versatile Rust crate for managing collections with dual functionalities: index-based and map-based data structures, supporting both dense and sparse implementations efficiently."
keywords = ["indexed", "mapped", "collections", "datastructures", "rust"]
categories = ["data-structures", "algorithms", "parsing", "asynchronous", "finance"]
license     = "MIT OR Apache-2.0"
