[dependencies.icentral-deps]
path = "../icentral-deps"
version = "0.1.0"
[package]
edition = "2021"
name = "icentral-test-fast-brandes"
version = "0.1.0"
description = "Highly optimized Brandes algorithm for computing betweenness centrality in network graphs."
keywords = ["brandesalgorithm", "betweennesscentralit", "networkanalysis", "graphtheory", "optimization"]
categories = ["algorithms", "science", "mathematics", "network-programming", "visualization"]
