[dependencies.icentral-3p]
path = "../icentral-3p"
version = "0.1.0"
[dependencies.icentral-mindexed-map]
path = "../icentral-mindexed-map"
version = "0.1.0"
[dependencies.icentral-nodeid]
path = "../icentral-nodeid"
version = "0.1.0"
[package]
edition = "2021"
name = "icentral-visit-markers"
version = "0.1.0"
description = "A Rust crate for managing and tracking node visitations in graph traversal algorithms, supporting both indexed and mapped storage structures."
keywords = ["graph", "traversal", "node", "visit", "tracking"]
categories = ["data-structures", "algorithms", "development-tools", "mathematics", "science"]
license     = "MIT OR Apache-2.0"
