[dependencies.icentral-deps]
path = "../icentral-deps"
version = "0.1.0"
[dependencies.icentral-graph-interface]
path = "../icentral-graph-interface"
version = "0.1.0"
[dependencies.icentral-mindexed-map]
path = "../icentral-mindexed-map"
version = "0.1.0"
[dependencies.icentral-mucid]
path = "../icentral-mucid"
version = "0.1.0"
[dependencies.icentral-nodeid]
path = "../icentral-nodeid"
version = "0.1.0"
[dependencies]
renew-traits = "0.1.0"
[package]
edition = "2021"
name = "icentral-mucid-map"
version = "0.1.0"
description = "Maps between NodeId and MucId using a high-performance, extensible Rust data structure called MucIdMap. Ideal for optimized node-based applications."
keywords = ["nodeid", "mucid", "mapping", "rust", "datastructure"]
categories = ["algorithms", "data-structures", "network-programming", "mathematics", "parsing"]
