[dependencies.icentral-3p]
path = "../icentral-3p"
version = "0.1.0"
[dependencies.icentral-bcc]
path = "../icentral-bcc"
version = "0.1.0"
[dependencies.icentral-edges]
path = "../icentral-edges"
version = "0.1.0"
[dependencies.icentral-errors]
path = "../icentral-errors"
version = "0.1.0"
[dependencies.icentral-graph]
path = "../icentral-graph"
version = "0.1.0"
[dependencies.icentral-graph-hash]
path = "../icentral-graph-hash"
version = "0.1.0"
[dependencies.icentral-graph-interface]
path = "../icentral-graph-interface"
version = "0.1.0"
[dependencies.icentral-nodeid]
path = "../icentral-nodeid"
version = "0.1.0"
[package]
edition = "2021"
name = "icentral-largest-bcc"
version = "0.1.0"
description = "A Rust crate for computing and analyzing the largest biconnected components in graphs, providing insights into node and edge distributions in terms of centrality metrics."
keywords = ["biconnectedcomponent", "graphtheory", "centrality", "networkanalysis", "algorithms"]
categories = ["algorithms", "data-structures", "network-programming", "science", "visualization"]
