[dependencies.icentral-3p]
path = "../icentral-3p"
version = "0.1.0"
[dependencies.icentral-mindexed-map]
path = "../icentral-mindexed-map"
version = "0.1.0"
[dependencies.icentral-nodeid]
path = "../icentral-nodeid"
version = "0.1.0"
[package]
edition = "2021"
name = "icentral-path-counts"
version = "0.1.0"
description = "A crate for managing path counts of nodes in graph-like structures, designed for efficient performance in computational graph analysis."
keywords = ["path", "nodes", "graph", "algorithm", "compute"]
categories = ["algorithms", "data-structures", "simulation", "science", "mathematics"]
license     = "MIT OR Apache-2.0"
