[dependencies.icentral-3p]
path = "../icentral-3p"
version = "0.1.0"
[dependencies.icentral-mindexed-map]
path = "../icentral-mindexed-map"
version = "0.1.0"
[dependencies.icentral-nodeid]
path = "../icentral-nodeid"
version = "0.1.0"
[package]
edition = "2021"
name = "icentral-subgraph-map"
version = "0.1.0"
description = "Facilitates efficient subgraph map management within large-scale graph structures, focusing on concurrency and safe data handling using Rust's memory sharing utilities."
keywords = ["subgraph", "graphstructure", "concurrency", "network", "rust"]
categories = ["data-structures", "concurrency", "network-programming", "memory-management"]
