[dependencies.icentral-deps]
path = "../icentral-deps"
version = "0.1.0"
[dependencies.icentral-edge]
path = "../icentral-edge"
version = "0.1.0"
[package]
edition = "2021"
name = "icentral-errors"
version = "0.1.0"
