[dependencies.icentral-3p]
path = "../icentral-3p"
version = "0.1.0"
[dependencies.icentral-mock]
path = "../icentral-mock"
version = "0.1.0"
[dependencies.icentral-nodeid]
path = "../icentral-nodeid"
version = "0.1.0"
[dependencies.icentral-scores]
path = "../icentral-scores"
version = "0.1.0"
[package]
edition = "2021"
name = "icentral-match"
version = "0.1.0"
description = "Provides constructs for graph-based computations and detailed analysis of betweenness centrality within undirected graphs."
keywords = ["graphtheory", "networkanalysis", "dachshund", "graphalgorithms"]
license     = "MIT OR Apache-2.0"
categories = ["algorithms", "science", "simulation", "mathematics"]
