[dependencies.icentral-deps]
path = "../icentral-deps"
version = "0.1.0"
[dependencies.icentral-component]
path = "../icentral-component"
version = "0.1.0"
[dependencies.icentral-edges]
path = "../icentral-edges"
version = "0.1.0"
[dependencies.icentral-errors]
path = "../icentral-errors"
version = "0.1.0"
[dependencies.icentral-graph-interface]
path = "../icentral-graph-interface"
version = "0.1.0"
[dependencies.icentral-neighbors]
path = "../icentral-neighbors"
version = "0.1.0"
[dependencies.icentral-nodeid]
path = "../icentral-nodeid"
version = "0.1.0"
[dependencies.icentral-scores]
path = "../icentral-scores"
version = "0.1.0"
[package]
edition = "2021"
name = "icentral-parallel-brandes"
version = "0.1.0"
description = "Efficient parallel computation of betweenness centrality using Brandes' algorithm in large graphs, leveraging Rust's concurrency model."
keywords = ["brandes", "parallel", "betweenness", "centrality", "graph"]
categories = ["algorithms", "concurrency", "mathematics", "network-programming", "simulation"]
