[dependencies.icentral-3p]
path = "../icentral-3p"
version = "0.1.0"
[dependencies.icentral-bbfs]
path = "../icentral-bbfs"
version = "0.1.0"
[dependencies.icentral-component]
path = "../icentral-component"
version = "0.1.0"
[dependencies.icentral-mindexed-map]
path = "../icentral-mindexed-map"
version = "0.1.0"
[dependencies.icentral-nodeid]
path = "../icentral-nodeid"
version = "0.1.0"
[dependencies.icentral-rbfs]
path = "../icentral-rbfs"
version = "0.1.0"
[dependencies.icentral-scores]
path = "../icentral-scores"
version = "0.1.0"
[dependencies.icentral-workspace]
path = "../icentral-workspace"
version = "0.1.0"
[package]
edition = "2021"
name = "icentral-workspace-map"
version = "0.1.0"
description = "A Rust crate for managing workspaces in a graph structure, utilizing a MaybeIndexedMap for efficient node-to-workspace mapping. Features search algorithms for graph traversal."
keywords = ["graph", "workspace", "map", "bfs", "sim"]
categories = ["data-structures", "algorithms", "science", "simulation"]
