[dependencies.icentral-deps]
path = "../icentral-deps"
version = "0.1.0"
[dependencies.serde]
features = [ "derive" ]
version = "1.0.210"
[dependencies.serde_derive]
version = "1.0.210"
[dependencies.serde_json]
version = "1.0.128"
[package]
edition = "2021"
name = "icentral-json"
version = "0.1.0"
