[dependencies.icentral-3p]
path = "../icentral-3p"
version = "0.1.0"
[dependencies.serde]
features = [ "derive" ]
version = "1.0.210"
[dependencies.serde_derive]
version = "1.0.210"
[dependencies.serde_json]
version = "1.0.128"
[package]
edition = "2021"
name = "icentral-json"
version = "0.1.0"
description = "A Rust crate facilitating the creation and serialization of JSON structures with two-level named member hierarchies using macros."
keywords = ["rust", "json", "serialization", "macros", "nestedstructures"]
categories = ["data-structures", "parsing", "network-programming"]
license     = "MIT OR Apache-2.0"
