[dependencies.icentral-deps]
path = "../icentral-deps"
version = "0.1.0"
[package]
edition = "2021"
name = "icentral-test-basic-icentral"
version = "0.1.0"
description = "Provides foundational utilities for basic testing within the iCentral framework in Rust 2021 edition."
keywords = ["icentral", "testing", "rust", "utilities", "framework"]
categories = ["development-tools"]
