[dependencies.icentral-deps]
path = "../icentral-deps"
version = "0.1.0"
[dependencies.icentral-edge]
path = "../icentral-edge"
version = "0.1.0"
[dependencies.icentral-neighbors]
path = "../icentral-neighbors"
version = "0.1.0"
[dependencies.icentral-nodeid]
path = "../icentral-nodeid"
version = "0.1.0"
[dependencies]
renew-traits = "0.1.0"
[package]
edition = "2021"
name = "icentral-label-map"
version = "0.1.0"
description = "Efficiently manage label mappings within directed graphs, supporting complex node and edge transformations."
keywords = ["labelmap", "graphtheory", "nodemapping", "datastructures", "directedgraphs"]
categories = ["data-structures", "algorithms", "science", "visualization"]
