[dependencies.icentral-3p]
path = "../icentral-3p"
version = "0.1.0"
[dependencies.icentral-nodeid]
path = "../icentral-nodeid"
version = "0.1.0"
[package]
edition = "2021"
name = "icentral-mucid"
version = "0.1.0"
description = "A Rust crate for managing Minimum Union Cycle IDs in graph nodes, providing easy-to-use traits and macros for interacting with node identifiers within complex graph structures."
keywords = ["graphtheory", "minimumunioncycle", "identifiers", "rust", "efficient"]
categories = ["algorithms", "data-structures", "mathematics", "parsing", "development-tools"]
